export const MONTH_INGREDIENTS = 'MONTH_INGREDIENTS';
export const DATE_CHANGE = 'DATE_CHANGE';
export const GET_RECIPE = 'GET_RECIPE';
export const ENTER_INGREDIENTS = 'ENTER_INGREDIENTS';
export const ALL_INGREDIENTS = 'ALL_INGREDIENTS';
export const SET_INGREDIENT = 'SET_INGREDIENT'
